name: Manual Package CI

on:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'docs/**'
      - 'README.md'

env:
  IMAGE_NAME: ghcr.io/ilogtail/loong-operator

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24.2

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ilogtail --password-stdin

      - name: Run lint
        run: make lint

      - name: Run test
        run: make test
      
      - name: Run dockerx build
        run: |
          make docker-buildx IMAGE=${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Run docker-push
        run: |
          make docker-push IMAGE=${{ env.IMAGE_NAME }}:${{ env.VERSION }}